name: IDFM Daily Sync

on:
  schedule:
    - cron: '0 0 * * *' # Tous les soirs à minuit
  workflow_dispatch: # Permet de lancer manuellement pour tester

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Autorise l'action à modifier les fichiers du repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Script
        run: go run .

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git pull

          git add *.json
          
          if git diff --cached --quiet; then
            echo "Aucun changement détecté dans les données."
          else
            git commit -m "chore: update IDFM data (stops & lines) [skip ci]"
            git push
          fi
